baseURL = 'https://berthon.dev/'
languageCode = 'en-us'
title = 'Romain Berthon'
theme = 'rocinante'

paginate = 10

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "favicon.ico"
  about = """
Software developer, *DD and F# enthusiast
"""

  [[params.links]]
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/RomainTrm"
      new_tab = true
    [[params.links.link]]
      name = "Bsky"
      href = "https://bsky.app/profile/berthon.dev"
      new_tab = true
    [[params.links.link]]
      name = "LinkedIn"
      href = "https://fr.linkedin.com/in/romain-berthon-254977101"
      new_tab = true